theme: jekyll-theme-slate
title: Covid-19 data
description: Aoteaora New Zealand, 2020

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
  

page-col: "#FFFFFF"
